### ISSUE TITLE
Rain animation shown when ground cover indicates it should be snow

### ISSUE THREAD

**Issue by PitchBright** [TheWeatherPony/TheSeasonsMod#1]
In the Spring, when there's precipitation in a biome (Extreme Hills for example) that would normally snow (in the Winter), the rain falling animation is showing, as snow tiles accumulate on the ground.

Version: Beta8c3

**Comment by TheWeatherPony** [comment]
Fixed for next version.

**Comment by TheWeatherPony** [comment]
wanted to explain - there's a bug that wasn't fixed correctly in the base code, which I managed to expose just like before. I previously thought the bug was fixed, but it wasn't. My "fix" is to change the seasonal constant multipliers by a very tiny amount, resulting in slightly different temperatures.

**Comment by jredfox** [comment]
ok it's rain animation and the rain sound it is physically raining then it places snow blocks in spring in the extreme hills biome.  it only does it in extreme hill type biomes. i tested this. there is more bugs let me file them. I have been unable to file bugs do to moving/being sick

**Comment by TheWeatherPony** [comment]
In some locations in the base code (outside of my control), the "freezing temperature" is equal to and less than.15. In others, it's only less than .15, not equal to. Extreme Hills in Spring for 8c4 and older is exactly .15, which leads to the experienced inconsistency.
As I had been saying, the problem was not within my code. The next version works around this by slightly increasing the temperature to .1502. This is a problem with the base game, and I will follow up by looking at a snapshot of the upcoming version and report it to the developers as necessary, if it still exists.

**Comment by jredfox** [comment]
the bug still occurs in beta8c4 the latest private edition. is this fixed in your next update or was this supose to be fixed in beta8c4? 
http://imgur.com/SHeohD3

**Comment by PitchBright** [comment]
Read what the man wrote. He said "Fixed for next version." and then closed the issue. Quit wasting his time.

**Comment by TheWeatherPony** [comment]
Reported as MC issue 96544: https://bugs.mojang.com/browse/MC-96544
