### ISSUE TITLE
[ModIncompatibility] Seasons@Twilight Forest

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#46]
Version: beta9
Crash Report: http://pastebin.com/RR9quhwb

When twilight forest is installed seasons crashes before it can load the main menu

**Comment by TheWeatherPony** [comment]
The compatibility problem with Twilight Forgest is derived from the expanded support for seasonal textures. Twilight Forest is getting textures from other blocks in order to create it's own.

**Comment by jredfox** [comment]
Ok like the raw beef and leaves. I guess you need to add custom support. Why did it work in previous versions?

**Comment by TheWeatherPony** [comment]
It worked it previous versions because I hadn't expanded support for seasonal block icons until the recently released version, and Twilight Forest is trying to get a block icon for one of the newly supported blocks. There is no world at that point, so the proper seasonal icon cannot possibly be identified.

**Comment by jredfox** [comment]
ok

**Comment by TheWeatherPony** [comment]
This particular issue has been fixed for the next version. There may be other, near-identical issues together with Twilight Forest which cause the same type of problem, but this specific one has been addressed.

The stack trace also warned me about another problem, which I have now also fixed.
