### ISSUE TITLE
[Client] Minecraft Console Is Saying Texture Errors

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#47]
Console: http://pastebin.com/ixsP9uYD

I started up minecraft (Client) with the console open all the way up to creating a new world then saving and quiting. **Launching minecraft is from line 1 to line 371** . **There are some texture errors from 158-371. Forge said that there are 195 missing textures**.

**Comment by PitchBright** [comment]
Those are all the textures that support growth changes by season… and that users can add themselves (via resourcepack I believe).

**Comment by jredfox** [comment]
ok well then forge is confused.

**Comment by PitchBright** [comment]
No, you are confused. The textures ARE missing, because YOU haven't added them ;)

**Comment by TheWeatherPony** [comment]
These are missing optional seasonal textures/icons - if they exist, they will be used instead of the normal ones, during the corresponding season. The game does not understand the concept of "optional icons," so spits out those messages. This is not a bug, but is an amusing quirk from vanilla/Forge.

**Comment by jredfox** [comment]
ok
