### ISSUE TITLE
Seasons performance needs to be inproved

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#5]
an example of running 1 client and 1 server with one person on not moving that much around. Again I am tired most of the ram was from the client but, that was the total ram 
http://imgur.com/7q9bx6Z
version: beta8c3

**Comment by PitchBright** [comment]
Runs fine on my server. Please provide server specs.

**Comment by jredfox** [comment]
yeah but, it could use some tweaks and optimizations. if you run a client and a server with just seasons it's 3.5g if you actually start to play. I didn't even go that far. What server specs? I said it takes alot of ram that's all.
http://www.mediafire.com/download/9u46p77wrqkzhse/SeasonsServerPackbeta8c3.zip

**Comment by PitchBright** [comment]
It runs at whatever "g" YOU set it to. 

&

Runs fine on my server. Please provide server specs.

**Comment by jredfox** [comment]
I gave it 5g (server) but, only used 3.5g together (server/client). when I give it ram it only cached what it needs. I noticed it also does this in minecraft to.  I am unsure if it can run on 1g with a 1g client and be lag free like on my pc that it would be vanilla.  I gave my client 1g

**Comment by jredfox** [comment]
I think if the weather pony could make seasons he could also get both client and server to run on 1g with some tweaks / optimizations with alot less lag. The client appears to be a problem. in that picture the amount of ram was on the client. it also has this in vanilla were it allocates ram of you move but, is more triggered by seasons.

**Comment by PitchBright** [comment]
Telling us how much RAM you allocated to minecraft… is NOT the same thing as providing specs to your server. You don't know squat about programming, so where do you get off saying you think it could be made with optimizations? Yes, in your dreams, it would run better, on your computer… but that doesn't make it do-able, letalone worth the time and effort. The problem is your computer, not the mod. it runs fine on my server. The end.

**Comment by PitchBright** [comment]
For the record… I get 40FPS with 100 mods + Seasons… running both a server and the client, on my 5 year old imac. It's ain't the mod… it's something on YOUR end.

**Comment by jredfox** [comment]
what's your processor? mine is an i55 something. how much ram do you use? did you fly around?

**Comment by TheWeatherPony** [comment]
As a previous part of testing for performance issues, bugs, and possible enhancements, I joined PitchBright on a private server he was running with many, many mods on the same computer which he was also running his client on. Since his computer is 5 years old, it likely has a weaker processer and only up to 4GB of RAM - which needed to be split between his OS, his client, the dedicated server, Skype, TeamSpeak3, and everything else we were using. He likely only had 1GB for his server and 1.5-2GB for his client. When we screen-shared with each other, I saw a smooth frame rate on his end from my computer - as I was looking at my avatar through his eyes. During this testing, we did fly around a fair bit while testing for concerns involving snow. While this was a while ago, the mod's base code did not change a significant degree.

On the other hand, I admit the last couple of versions have had a couple of loading performance hits - these have, however, already been cleaned up for the next version, which Pitch is helping me test as I continue developing. Regardless, my code has only ever added a few MB to the RAM requirement, at most, and uses a surprisingly little amount of CPU, after things settle down (using without my code as a baseline).

**Comment by jredfox** [comment]
yeh but, you admitted that that the recent ones were laggy. I only get 40fps running on 1g I normaly get in vanly 60-110fps on 1g so I think this can be an enhancement for the future.

**Comment by TheWeatherPony** [comment]
While I admitted the last couple of builds were a bit slower during loading, the biggest component I've been working with for those builds is the new crop system - which I already said has been fixed in many different ways for the next build, including performance-wise.
Any slowness involved is either fixed for the next version, or is a new part of the new code that can't be removed without disabling components - therefore, the issue is closed.

As for the exact issue reported, there are 48 things running on your computer, sharing 74% of your CPU and 3.5GB of RAM, and of which only 1 or 2 are an instance of game - which is itself running an unspecified number of mods other alongside my own. The breakup of this 74% CPU and 3.5GB of RAM usage is unspecified, and there is no baseline established as comparison, other than in fps, which was given after the issue was closed. I therefore have nothing to work on other than hunches. Regardless, the problem is either fixed or is a new standard.

For your memory concern, TSM has always used very little RAM, as I tend to be overly optimization-focused about my code, in _all_ regards. This can be seen from my changelogs, where my removing 1KB of one-time client-server I/O is considered highly important, almost more so than new added features. If there does happen to remain issues in performance after the next version, my history suggests I will come back and optimize the code wherever possible, anyways; so any such issue may get cleaned up, regardless. Actual RAM usage by Java programs is rarely seen my the task manager, however, because Java itself decides when to release it's unused memory back to the computer - Java will hold on to memory as long as it wants, even after it's no longer needed.

**Comment by jredfox** [comment]
You are saying you can't do optimizations to make it run smoother like mojang does all the time?

**Comment by TheWeatherPony** [comment]
I'm saying that Mojang has enough un-optimized code to make those optimizations. Their biggest optimization updates can increase fps from 20 to 60, because such optimizations are possible due to enough un-optimized code, while my biggest optimization updates can only decrease already tiny resource requirements - other than possibly the crop code settings which, as I've already said, have already been optimized for performance for the next version. 

I have already streamlined the code that would likely be the culprit for any recent performance problems within my code, so have closed this issue for either completion, or for an inability to get fixed - any inability being with the newer, more complicated code, not for incompetency.

**Comment by jredfox** [comment]
ok cool
