### ISSUE TITLE
Seasons Transitions Are Off [Example:Spring to Autumn]

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#52]
Log: http://pastebin.com/iac37BbG
Version: beta10
Video: https://www.youtube.com/watch?v=JGg7K16B9V4

At day 6 seasons transitions the next season at day 7 but, the wrong season.  Here are what the seasons default transitional settings are by default;

winter to summer
spring to Autumn
summer to Winter
Autumn to Spring

**Comment by TheWeatherPony** [comment]
Fixed bug where the seasonal chat display message says "season.Autumn", etc. instead of the season's localized name.

Fixed bug where the "next season" for all seasons was a season ahead, leading the mod to alternate between two opposing seasons.

Fixed bug where seasonal affliction messages were not sent correctly. This impacted both seasonal overlays and hot/cold vignettes, as well as hypothermic slowness.

Fixed bug where seasonal messages could not be longer than 127 bytes. Limit increased significantly for server-to-client biome information message.

**Comment by jredfox** [comment]
ok well I don't think it just displayed season as winter when it was winter it could snow if it wasn't it couldn't snow.

**Comment by TheWeatherPony** [comment]
...huh?

**Comment by PitchBright** [comment]
@jredfox Use punctuation man. 

It's all good… Pony said he fixed it:
"Fixed bug where the "next season" for all seasons was a season ahead, leading the mod to alternate between two opposing seasons."

**Comment by jredfox** [comment]
don't worry about it if it's fixed.
