### ISSUE TITLE
Snow Tiles Not Disappearing When a grass block /ice block underneath it

### ISSUE THREAD

**Issue by jredfox** [TheWeatherPony/TheSeasonsMod#56]
Version: beta 10
Images: http://imgur.com/a/iTz2T

Snow Tiles Not Disappearing When a grass block /ice block underneath it

**Comment by TheWeatherPony** [comment]
Fixed bug that stopped snow from collapsing into air blocks.

Snow disappearing when the block under it gets removed is the vanilla functionality, and is fixed/improved by making the snow collapse down the way within this mod, rather than getting removed outright. Regrettably, the collapse is currently instantaneous.
