### ISSUE TITLE
pml enderio incompatibility causing a crash

### ISSUE THREAD

**Issue by superdude808** [TheWeatherPony/TheSeasonsMod#88]
ok while playing minecraft the game just randomly crashes here is the crash log http://pastebin.com/6wxHuz76
it is a weird interaction with enderio and pml apparently trying to update the attributes of a non living entity

**Comment by superdude808** [comment]
not sure if it is pml ineracting with enderio but it's what the guys in the enderio issue reporting section here on git hub have said might be the problem

**Comment by jredfox** [comment]
there is no conflicting from pml sorry.  "at weatherpony.pml.premain.ReplacementMainThread.run(ReplacementMainThread.java:104)
 " is at every single crash report if seasons mod is installed even if it's two other mods conflicting.  there is no more details on pml or seasons causing any issues. if there was more then that line then I would be worried.  try  deleting your configs , updating all of the mods to the latest mc version that you want then try it again and see if the errors persist. if they do contact enderiq.  by updating all the mods I mean it. enderiq might be using one of the apis that enderiq or outdated builcraft/outdated thermal dynamics can cause.  I don't want to close this issue just in case, so theweatherpony will close it. **also don't use the same world to test it because, it has some kind of corrupt data that is going on.** I would test it only after you update all the mods, remove pml, seasons , mod-dev(season required mod) and if it still crashes it's not pml/seasons. if it only occurs when pml / seasons and you can ganrentee that that crash doesn't happen without it then it is pml/seasons. otherwise it is most likely a crash from outdated mods.  try updating all of your mods, delete old configs, reconfig, try again and do  what I said before.

**Comment by TheWeatherPony** [comment]
As he was saying, that line is going be there whenever you run a client with the mod - servers get rid of it by running in a thread other than the one the game starts with. "ReplacementMainThread" simply replaces the main (original) thread (task/process/job/execution line/etc.) due to limitations buried in advanced Java trickery that is being used to make things happen properly.

@jredfox which mod has some kind of corrupt data going on?

**Comment by jredfox** [comment]
his world is corrupt by two or more mods conflicting or updating.  I think forge thinks it's doing one thing with the saved chunks and the code loaded is doing another thing. I had this problem developing modpacks.
