### ISSUE TITLE
Local Weather & Storms is not Compatible

### ISSUE THREAD

**Issue by VirtualGaming1** [TheWeatherPony/TheSeasonsMod#95]
this is happining the and it is saying server side. don't know right now but it could be the Local Weather & Storms Mod.
[Season Bug report.txt](https://github.com/TheWeatherPony/TheSeasonsMod/files/362514/Season.Bug.report.txt)

**Comment by VirtualGaming1** [comment]
Just did a quick test and the result is that The Season Mod is not Compatible with Local Weather & Storms Mod as of the Temp editing error for server (SSP) Side.
:cry:

**Comment by jredfox** [comment]
thanks for making this suggestion I made this before and it was ignored.

**Comment by TheWeatherPony** [comment]
Fixed for next release.
jred, searching through this repo's issues with "weather" doesn't come up with anything you've reported involving that mod. Would you mind letting me know which issue number it was that you reported the error involving this mod? (Virtual isn't reporting a suggestion)
Also... this was already fixed for the next releases, I just haven't done any releases since I coded the fix :P

**Comment by VirtualGaming1** [comment]
can not wait to see this release out so i can test it with the weather mod. and @TheWeatherPony were you able to look at the Bug report.txt file that i uploaded to here?

**Comment by jredfox** [comment]
theweatherpony I reported this as an enchancement or suggestion a while ago a couple times.  I am busy but, will look for it later.
